package land.lark.model;

public class Usr {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column usr.code
	 * @mbg.generated
	 */
	private String code;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column usr.name
	 * @mbg.generated
	 */
	private String name;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column usr.code
	 * @return  the value of usr.code
	 * @mbg.generated
	 */
	public String getCode() {
		return code;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column usr.code
	 * @param code  the value for usr.code
	 * @mbg.generated
	 */
	public void setCode(String code) {
		this.code = code;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column usr.name
	 * @return  the value of usr.name
	 * @mbg.generated
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column usr.name
	 * @param name  the value for usr.name
	 * @mbg.generated
	 */
	public void setName(String name) {
		this.name = name;
	}
}