package land.lark.mapper;

import java.util.List;
import land.lark.model.Usr;

/**
 * UsrMapper
 * 
 * @author yonxu
 */
public interface UsrMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table usr
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(String code);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table usr
	 * @mbg.generated
	 */
	int insert(Usr usr);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table usr
	 * @mbg.generated
	 */
	Usr selectByPrimaryKey(String code);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table usr
	 * @mbg.generated
	 */
	List<Usr> selectAll();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table usr
	 * @mbg.generated
	 */
	int updateByPrimaryKey(Usr usr);
}