logging:
  config: classpath:log4j2.xml
spring:
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/larkland
    username: larkland
    password: larkland
    driverClassName: org.postgresql.Driver